/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : VelocityStateSensor_VelocityStateSensorProtocol_sm.sm
 */

#include "urn_jaus_jss_mobility_VelocityStateSensor_1_0/Messages/MessageSet.h"
#include "urn_jaus_jss_mobility_VelocityStateSensor_1_0/VelocityStateSensor_VelocityStateSensorProtocol.h"
#include "include/urn_jaus_jss_mobility_VelocityStateSensor_1_0/VelocityStateSensor_VelocityStateSensorProtocol_sm.h"

using namespace statemap;

namespace urn_jaus_jss_mobility_VelocityStateSensor_1_0
{
    // Static class declarations.
    VelocityStateSensor_VelocityStateSensorProtocol_SM_Ready VelocityStateSensor_VelocityStateSensorProtocol_SM::Ready("VelocityStateSensor_VelocityStateSensorProtocol_SM::Ready", 0);
    VelocityStateSensor_VelocityStateSensorProtocol_SM_Internally_Generated_State_DO_NOT_USE VelocityStateSensor_VelocityStateSensorProtocol_SM::Internally_Generated_State_DO_NOT_USE("VelocityStateSensor_VelocityStateSensorProtocol_SM::Internally_Generated_State_DO_NOT_USE", 1);

    void VelocityStateSensor_VelocityStateSensorProtocolState::QueryVelocityStateTransition(VelocityStateSensor_VelocityStateSensorProtocolContext& context)
    {
        Default(context);
        return;
    }

    void VelocityStateSensor_VelocityStateSensorProtocolState::QueryVelocityStateTransition(VelocityStateSensor_VelocityStateSensorProtocolContext& context, QueryVelocityState& msg, unsigned int& sender)
    {
        Default(context);
        return;
    }

    void VelocityStateSensor_VelocityStateSensorProtocolState::Default(VelocityStateSensor_VelocityStateSensorProtocolContext& context)
    {
        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Default"
                << std::endl;
        }

        throw (
            TransitionUndefinedException(
                context.getState().getName(),
                context.getTransition()));

        return;
    }

    void VelocityStateSensor_VelocityStateSensorProtocol_SM_Ready::QueryVelocityStateTransition(VelocityStateSensor_VelocityStateSensorProtocolContext& context, QueryVelocityState& msg, unsigned int& sender)
    {
        VelocityStateSensor_VelocityStateSensorProtocol& ctxt(context.getOwner());

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : VelocityStateSensor_VelocityStateSensorProtocol_SM::Ready"
            << std::endl;
        }

        VelocityStateSensor_VelocityStateSensorProtocolState& endState = context.getState();

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: VelocityStateSensor_VelocityStateSensorProtocol_SM::Ready::QueryVelocityStateTransition(QueryVelocityState& msg, unsigned int& sender)"
                << std::endl;
        }

        context.clearState();
        try
        {
            ctxt.sendReportVelocityStateAction(msg, sender);
            if (context.getDebugFlag() == true)
            {
                std::ostream& str = context.getDebugStream();

                str << "EXIT TRANSITION : VelocityStateSensor_VelocityStateSensorProtocol_SM::Ready::QueryVelocityStateTransition(QueryVelocityState& msg, unsigned int& sender)"
                    << std::endl;
            }

            context.setState(endState);
        }
        catch (...)
        {
            context.setState(endState);
            throw;
        }

        return;
    }

    void VelocityStateSensor_VelocityStateSensorProtocol_SM_Internally_Generated_State_DO_NOT_USE::QueryVelocityStateTransition(VelocityStateSensor_VelocityStateSensorProtocolContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : VelocityStateSensor_VelocityStateSensorProtocol_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: VelocityStateSensor_VelocityStateSensorProtocol_SM::Internally_Generated_State_DO_NOT_USE::QueryVelocityStateTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : VelocityStateSensor_VelocityStateSensorProtocol_SM::Internally_Generated_State_DO_NOT_USE::QueryVelocityStateTransition()"
                << std::endl;
        }


        return;
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
