/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol_sm.sm
 */

#include "urn_jaus_jss_mobility_CDServiceDef_1_0/Messages/MessageSet.h"
#include "urn_jaus_jss_mobility_CDServiceDef_1_0/CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol.h"
#include "include/urn_jaus_jss_mobility_CDServiceDef_1_0/CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol_sm.h"

using namespace statemap;

namespace urn_jaus_jss_mobility_CDServiceDef_1_0
{
    // Static class declarations.
    CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol_SM_Ready CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol_SM::Ready("CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol_SM::Ready", 0);
    CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol_SM_Internally_Generated_State_DO_NOT_USE CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol_SM::Internally_Generated_State_DO_NOT_USE("CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol_SM::Internally_Generated_State_DO_NOT_USE", 1);

    void CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocolState::ReportIdentificationTransition(CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocolContext& context)
    {
        Default(context);
        return;
    }

    void CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocolState::ReportIdentificationTransition(CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocolContext& context, ReportIdentification& msg, unsigned int& sender)
    {
        Default(context);
        return;
    }

    void CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocolState::ReportServicesTransition(CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocolContext& context)
    {
        Default(context);
        return;
    }

    void CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocolState::ReportServicesTransition(CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocolContext& context, ReportServices& msg, unsigned int& sender)
    {
        Default(context);
        return;
    }

    void CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocolState::Default(CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocolContext& context)
    {
        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "TRANSITION   : Default"
                << std::endl;
        }

        throw (
            TransitionUndefinedException(
                context.getState().getName(),
                context.getTransition()));

        return;
    }

    void CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol_SM_Ready::ReportIdentificationTransition(CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocolContext& context, ReportIdentification& msg, unsigned int& sender)
    {
        CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol& ctxt(context.getOwner());

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol_SM::Ready"
            << std::endl;
        }

        CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocolState& endState = context.getState();

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol_SM::Ready::ReportIdentificationTransition(ReportIdentification& msg, unsigned int& sender)"
                << std::endl;
        }

        context.clearState();
        try
        {
            ctxt.sendQueryIdentificationAction(msg, sender);
            if (context.getDebugFlag() == true)
            {
                std::ostream& str = context.getDebugStream();

                str << "EXIT TRANSITION : CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol_SM::Ready::ReportIdentificationTransition(ReportIdentification& msg, unsigned int& sender)"
                    << std::endl;
            }

            context.setState(endState);
        }
        catch (...)
        {
            context.setState(endState);
            throw;
        }

        return;
    }

    void CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol_SM_Ready::ReportServicesTransition(CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocolContext& context, ReportServices& msg, unsigned int& sender)
    {
        CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol& ctxt(context.getOwner());

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol_SM::Ready"
            << std::endl;
        }

        CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocolState& endState = context.getState();

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol_SM::Ready::ReportServicesTransition(ReportServices& msg, unsigned int& sender)"
                << std::endl;
        }

        context.clearState();
        try
        {
            ctxt.sendQueryServicesAction(msg, sender);
            if (context.getDebugFlag() == true)
            {
                std::ostream& str = context.getDebugStream();

                str << "EXIT TRANSITION : CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol_SM::Ready::ReportServicesTransition(ReportServices& msg, unsigned int& sender)"
                    << std::endl;
            }

            context.setState(endState);
        }
        catch (...)
        {
            context.setState(endState);
            throw;
        }

        return;
    }

    void CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol_SM_Internally_Generated_State_DO_NOT_USE::ReportIdentificationTransition(CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocolContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol_SM::Internally_Generated_State_DO_NOT_USE::ReportIdentificationTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol_SM::Internally_Generated_State_DO_NOT_USE::ReportIdentificationTransition()"
                << std::endl;
        }


        return;
    }

    void CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol_SM_Internally_Generated_State_DO_NOT_USE::ReportServicesTransition(CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocolContext& context)
    {

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "LEAVING STATE   : CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol_SM::Internally_Generated_State_DO_NOT_USE"
            << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "ENTER TRANSITION: CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol_SM::Internally_Generated_State_DO_NOT_USE::ReportServicesTransition()"
                << std::endl;
        }

        if (context.getDebugFlag() == true)
        {
            std::ostream& str = context.getDebugStream();

            str << "EXIT TRANSITION : CapabilityDiscoveryServiceDef_CapabilityDiscoveryProtocol_SM::Internally_Generated_State_DO_NOT_USE::ReportServicesTransition()"
                << std::endl;
        }


        return;
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
